
version: '3.8'

services:
  todo-app:
    build: .
    #ports:
    #  - "3000:80"
    container_name: todo-app
    pull_policy: always
    restart: unless-stopped
    environment:
      - NODE_ENV=production
